---
name: Ansible Molecule
on:
  push:
    tags_ignore:
      - '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "ubuntu"
            tag: "latest"
          - image: "ubuntu"
            tag: "focal"
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Build an image from Dockerfile
        run: |
          docker build -t local/molecule-image:1.0.0 .
      - name: Test Ansible roles with Molecule
        uses: sudheer-v/molecule-action@1.0.0 
        with:
          image: ubuntu
          tag: latest
